"""Pre-seeded IB DP curriculum per subject.

Each entry is (code, title, ib_weight 1-5). Weights reflect rough exam emphasis;
tweak in the UI per topic later. These lists are intentionally pragmatic — IB
guides change; the UI lets you add/edit.
"""
from __future__ import annotations

CURRICULA: dict[str, list[tuple[str, str, int]]] = {
    # ---------------- Biology HL ----------------
    "Biology": [
        ("A1.1", "Water", 3),
        ("A1.2", "Nucleic acids", 4),
        ("A2.1", "Origins of cells", 2),
        ("A2.2", "Cell structure", 4),
        ("A2.3", "Viruses", 2),
        ("A3.1", "Diversity of organisms", 3),
        ("A3.2", "Classification and cladistics", 3),
        ("A4.1", "Evolution and speciation", 4),
        ("A4.2", "Conservation of biodiversity", 3),
        ("B1.1", "Carbohydrates and lipids", 3),
        ("B1.2", "Proteins", 4),
        ("B2.1", "Membranes and membrane transport", 4),
        ("B2.2", "Organelles and compartmentalization", 3),
        ("B2.3", "Cell specialization", 3),
        ("B3.1", "Gas exchange", 4),
        ("B3.2", "Transport", 4),
        ("B3.3", "Muscle and motility", 3),
        ("B4.1", "Adaptation to environment", 3),
        ("B4.2", "Ecological niches", 3),
        ("C1.1", "Enzymes and metabolism", 5),
        ("C1.2", "Cell respiration", 5),
        ("C1.3", "Photosynthesis", 5),
        ("C2.1", "Chemical signalling", 4),
        ("C2.2", "Neural signalling", 4),
        ("C3.1", "Integration of body systems", 4),
        ("C3.2", "Defence against disease", 4),
        ("C4.1", "Populations and communities", 3),
        ("C4.2", "Transfers of energy and matter", 3),
        ("D1.1", "DNA replication", 5),
        ("D1.2", "Protein synthesis", 5),
        ("D1.3", "Mutation and gene editing", 4),
        ("D2.1", "Cell and nuclear division", 5),
        ("D2.2", "Gene expression", 4),
        ("D2.3", "Water potential", 3),
        ("D3.1", "Reproduction", 4),
        ("D3.2", "Inheritance", 5),
        ("D3.3", "Homeostasis", 4),
        ("D4.1", "Natural selection", 4),
        ("D4.2", "Stability and change", 3),
        ("D4.3", "Climate change", 3),
    ],

    # ---------------- Chemistry HL ----------------
    "Chemistry": [
        ("S1.1", "Introduction to the particulate nature of matter", 3),
        ("S1.2", "The nuclear atom", 4),
        ("S1.3", "Electron configurations", 5),
        ("S1.4", "Counting particles by mass: the mole", 5),
        ("S1.5", "Ideal gases", 4),
        ("S2.1", "The ionic model", 4),
        ("S2.2", "The covalent model", 5),
        ("S2.3", "The metallic model", 3),
        ("S2.4", "From models to materials", 3),
        ("S3.1", "The periodic table: classification of elements", 4),
        ("S3.2", "Functional groups: classification of organic compounds", 5),
        ("R1.1", "Measuring enthalpy changes", 4),
        ("R1.2", "Energy cycles in reactions", 4),
        ("R1.3", "Energy from fuels", 3),
        ("R1.4", "Entropy and spontaneity (HL)", 4),
        ("R2.1", "How much? The amount of chemical change", 4),
        ("R2.2", "How fast? The rate of chemical change", 5),
        ("R2.3", "How far? The extent of chemical change", 5),
        ("R3.1", "Proton transfer reactions", 5),
        ("R3.2", "Electron transfer reactions", 5),
        ("R3.3", "Electron sharing reactions", 4),
        ("R3.4", "Electron-pair sharing reactions", 4),
    ],

    # ---------------- Math AA SL ----------------
    "Math AA": [
        ("1.1", "Operations with numbers in scientific notation", 2),
        ("1.2", "Arithmetic sequences and series", 4),
        ("1.3", "Geometric sequences and series", 4),
        ("1.4", "Financial applications", 3),
        ("1.5", "Laws of exponents and logarithms", 5),
        ("1.6", "Simple proof", 3),
        ("1.7", "Binomial theorem", 4),
        ("2.1", "Equations of straight lines", 3),
        ("2.2", "Functions, domain, range, inverse", 5),
        ("2.3", "Graphing functions", 4),
        ("2.4", "Key features of graphs", 4),
        ("2.5", "Composite and inverse functions", 4),
        ("2.6", "Quadratic functions and equations", 5),
        ("2.7", "Rational, exponential, log functions", 5),
        ("2.8", "Solving equations graphically/analytically", 4),
        ("3.1", "Right-angle and non-right triangle trig", 4),
        ("3.2", "Sine, cosine, area rules", 4),
        ("3.3", "Applications of trigonometry", 3),
        ("3.4", "The unit circle and radians", 5),
        ("3.5", "Trig identities and equations", 5),
        ("3.6", "Trig functions and graphs", 4),
        ("4.1", "Sampling and data", 2),
        ("4.2", "Statistical measures", 3),
        ("4.3", "Linear correlation and regression", 4),
        ("4.4", "Probability concepts", 4),
        ("4.5", "Probability distributions", 4),
        ("4.6", "Binomial distribution", 4),
        ("4.7", "Normal distribution", 5),
        ("5.1", "Introduction to differential calculus", 5),
        ("5.2", "Increasing/decreasing, tangents/normals", 5),
        ("5.3", "Differentiation rules", 5),
        ("5.4", "Integration as antidifferentiation", 5),
        ("5.5", "Definite integrals and area", 5),
        ("5.6", "Kinematics with calculus", 4),
    ],

    # ---------------- English Lang & Lit SL ----------------
    "English Lang & Lit": [
        ("1.1", "Readers, writers and texts — close reading", 5),
        ("1.2", "Literary devices and stylistic choices", 5),
        ("1.3", "Non-literary text types and conventions", 4),
        ("2.1", "Time and space — context of production/reception", 4),
        ("2.2", "Cultural and historical contexts", 4),
        ("2.3", "Comparative analysis across texts", 5),
        ("3.1", "Intertextuality — connecting texts", 4),
        ("3.2", "Global issues — selection and framing", 5),
        ("4.1", "Individual Oral preparation", 5),
        ("4.2", "Paper 1 guided analysis technique", 5),
        ("4.3", "Paper 2 comparative essay technique", 5),
        ("4.4", "Learner Portfolio entries", 3),
    ],

    # ---------------- Business Management SL ----------------
    "Business Management": [
        ("1.1", "Introduction to business management", 2),
        ("1.2", "Types of organizations", 3),
        ("1.3", "Business objectives", 3),
        ("1.4", "Stakeholders", 3),
        ("1.5", "External environment (STEEPLE)", 4),
        ("1.6", "Growth and evolution", 4),
        ("1.7", "Organizational planning tools", 3),
        ("2.1", "Introduction to HR management", 3),
        ("2.2", "Organizational structure", 4),
        ("2.3", "Leadership and management", 4),
        ("2.4", "Motivation and demotivation", 4),
        ("2.5", "Organizational culture", 3),
        ("3.1", "Introduction to finance", 3),
        ("3.2", "Sources of finance", 4),
        ("3.3", "Costs and revenues", 4),
        ("3.4", "Final accounts", 5),
        ("3.5", "Profitability and liquidity ratios", 5),
        ("3.6", "Cash flow", 4),
        ("3.7", "Investment appraisal", 4),
        ("3.8", "Budgets", 3),
        ("4.1", "Introduction to marketing", 3),
        ("4.2", "Marketing planning", 4),
        ("4.3", "Sales forecasting", 3),
        ("4.4", "Market research", 4),
        ("4.5", "The 7 Ps of the marketing mix", 5),
        ("5.1", "Introduction to operations management", 3),
        ("5.2", "Operations methods", 3),
        ("5.3", "Lean production and quality management", 4),
        ("5.4", "Location", 3),
        ("5.5", "Break-even analysis", 4),
        ("5.6", "Production planning", 3),
    ],

    # ---------------- Arabic ab initio SL ----------------
    # ---------------- Extended Essay (Core) ----------------
    "Extended Essay": [
        ("EE.1", "Choose subject and topic", 5),
        ("EE.2", "Formulate research question", 5),
        ("EE.3", "Source gathering and annotated bibliography", 4),
        ("EE.4", "Reflection 1 with supervisor", 3),
        ("EE.5", "Outline and structure", 4),
        ("EE.6", "First full draft", 5),
        ("EE.7", "Reflection 2 with supervisor", 3),
        ("EE.8", "Revisions and editing", 4),
        ("EE.9", "Final reflection (viva voce)", 3),
        ("EE.10", "Final submission with citations", 5),
    ],

    # ---------------- Theory of Knowledge (Core) ----------------
    "Theory of Knowledge": [
        ("TOK.1", "Core theme — Knowledge and the knower", 5),
        ("TOK.2", "Optional theme — Knowledge and technology", 3),
        ("TOK.3", "Optional theme — Knowledge and language", 3),
        ("TOK.4", "Optional theme — Knowledge and politics", 3),
        ("TOK.5", "AOK — Natural sciences", 4),
        ("TOK.6", "AOK — Human sciences", 4),
        ("TOK.7", "AOK — History", 4),
        ("TOK.8", "AOK — Mathematics", 4),
        ("TOK.9", "AOK — The arts", 3),
        ("TOK.10", "Exhibition — choose IA prompt", 5),
        ("TOK.11", "Exhibition — select 3 objects with commentary", 5),
        ("TOK.12", "Essay — analyse prescribed title", 5),
        ("TOK.13", "Essay — develop arguments and counter-arguments", 5),
        ("TOK.14", "Essay — final draft and citation", 5),
    ],

    # ---------------- CAS (Core) ----------------
    "CAS": [
        ("CAS.1", "Identify Creativity strand activities", 3),
        ("CAS.2", "Identify Activity strand", 3),
        ("CAS.3", "Identify Service strand", 3),
        ("CAS.4", "CAS project plan (collaborative)", 4),
        ("CAS.5", "Reflections on 7 learning outcomes", 4),
        ("CAS.6", "Three formal interviews with CAS coordinator", 3),
        ("CAS.7", "Final portfolio submission", 5),
    ],

    # ---------------- UCAT (UK medical/dental admissions test) ----------------
    "UCAT": [
        ("VR.1", "Verbal Reasoning — skim & scan technique", 5),
        ("VR.2", "Verbal Reasoning — true / false / can't tell", 5),
        ("VR.3", "Verbal Reasoning — main idea & inference", 4),
        ("VR.4", "Verbal Reasoning — timed practice (21m / 44Q)", 5),
        ("DM.1", "Decision Making — logic puzzles", 4),
        ("DM.2", "Decision Making — syllogisms", 4),
        ("DM.3", "Decision Making — Venn diagrams & probability", 5),
        ("DM.4", "Decision Making — recognising arguments", 4),
        ("DM.5", "Decision Making — timed practice (31m / 29Q)", 5),
        ("QR.1", "Quantitative Reasoning — percentages & ratios", 5),
        ("QR.2", "Quantitative Reasoning — speed/distance/time", 4),
        ("QR.3", "Quantitative Reasoning — tables & charts", 5),
        ("QR.4", "Quantitative Reasoning — keyboard shortcuts & calculator", 3),
        ("QR.5", "Quantitative Reasoning — timed practice (25m / 36Q)", 5),
        ("AR.1", "Abstract Reasoning — pattern types (shape/size/position)", 5),
        ("AR.2", "Abstract Reasoning — set A vs set B", 5),
        ("AR.3", "Abstract Reasoning — sequences & analogies", 4),
        ("AR.4", "Abstract Reasoning — timed practice (12m / 50Q)", 5),
        ("SJT.1", "Situational Judgement — appropriateness scale", 5),
        ("SJT.2", "Situational Judgement — importance scale", 5),
        ("SJT.3", "Situational Judgement — GMC Good Medical Practice", 4),
        ("SJT.4", "Situational Judgement — timed practice (26m / 69Q)", 5),
        ("FM.1", "Full mock under timed conditions", 5),
        ("FM.2", "Review of mock — error log per section", 5),
    ],

    # ---------------- Arabic ab initio SL ----------------
    "Arabic ab initio": [
        ("T1.1", "Identities — personal attributes & relationships", 4),
        ("T1.2", "Identities — daily routines, food and drink", 3),
        ("T1.3", "Identities — physical and psychological wellbeing", 3),
        ("T2.1", "Experiences — leisure, holidays, festivals", 3),
        ("T2.2", "Experiences — life stories and customs", 3),
        ("T3.1", "Human ingenuity — transport, technology", 3),
        ("T3.2", "Human ingenuity — entertainment and media", 3),
        ("T4.1", "Social organization — neighbourhood and city", 3),
        ("T4.2", "Social organization — education and the workplace", 4),
        ("T5.1", "Sharing the planet — environment, geography", 3),
        ("T5.2", "Sharing the planet — global issues", 3),
        ("G1", "Grammar — present tense verbs", 5),
        ("G2", "Grammar — past tense verbs", 5),
        ("G3", "Grammar — future tense and modal expressions", 4),
        ("G4", "Grammar — noun-adjective agreement", 5),
        ("G5", "Grammar — possessive constructions (idafa)", 4),
        ("G6", "Grammar — pronouns and prepositions", 4),
        ("S1", "Skill — reading comprehension strategies", 4),
        ("S2", "Skill — listening comprehension strategies", 4),
        ("S3", "Skill — writing short texts (email, message, blog)", 5),
        ("S4", "Skill — speaking and pronunciation", 5),
        ("V1", "Vocabulary — script and high-frequency words", 5),
    ],
}
